/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

import com.app.model.Cliente;
import com.app.model.Trabajador;

public class App {

    public static void main(String[] args) {
        Cliente cliente = new Cliente();
        cliente.setNombre("Juan");
        cliente.setEdad(60);
        cliente.setTelefono("55555-55-55555");
        cliente.setCredito(150.00);

        Trabajador trabajador = new Trabajador();
        trabajador.setNombre("Pedro");
        trabajador.setEdad(65);
        trabajador.setTelefono("66666-66-66666");
        trabajador.setSalario(1500.00);

        System.out.println(String.format("Nombre: %s | Edad: %d | Telefono: %s | Credito: %s",
                cliente.getNombre(),
                cliente.getEdad(),
                cliente.getTelefono(),
                cliente.getCredito()));

        System.out.println(String.format("Nombre: %s | Edad: %d | Telefono: %s | Salario: %s",
                trabajador.getNombre(),
                trabajador.getEdad(),
                trabajador.getTelefono(),
                trabajador.getSalario()));

    }
}