/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

import com.app.model.Persona;

public class App {

    public static void main(String[] args) {
        Persona persona = new Persona();

        persona.setNombre("Juan");
        persona.setEdad(60);
        persona.setTelefono("55555-55-5555");

        System.out.println("Nombre:" + persona.getNombre());
        System.out.println("Edad: " + persona.getEdad());
        System.out.println("Telefono: " + persona.getTelefono());
    }
}