/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

public class App {

    public static void main(String[] args) {

        compareIf(-1);
        incrementNumeroWhile();
        incrementDoWhile();
        incrementFor();
        estacionAnio();
    }

    public static void compareIf(int numeroIf){
        System.out.println("=====compareIf=====");
        if(numeroIf == 0)
            System.out.println("numeroIf es cero");
        else if (numeroIf < 0)
            System.out.println("numeroIf es negativo");
        else
            System.out.println("numeroIf es positivo");
    }

    public static void incrementNumeroWhile(){
        System.out.println("=====incrementNumeroWhile=====");
        int numeroWhile = 0;
        while(numeroWhile < 3){
            numeroWhile++;
            System.out.println(numeroWhile);
        }
    }

    public static void incrementDoWhile(){
        System.out.println("=====incrementDoWhile=====");
        int numeroWhile = 0;
        do{
           numeroWhile++;
        }while(numeroWhile<3);
        System.out.println(numeroWhile);
    }

    public static void incrementFor(){
        System.out.println("=====incrementFor=====");
        int numberoFor = 0;
        for(; numberoFor<=3; numberoFor++){
            System.out.println(numberoFor);
        }
    }

    public static void estacionAnio(){
        System.out.println("=====estacionAnio=====");
        String estacion = "verano";
        switch (estacion.toUpperCase()){
            case "PRIMAVERA":
            case "VERANO":
            case "OTOÑO":
            case "INVIERNO":
                System.out.println(estacion);
                break;
            default:
                System.out.println("La estación del año no existe");

        //Otra posible solucion para una logica diferente en cada case
        /*
        switch (estacion.toUpperCase()){
            case "PRIMAVERA":
                System.out.println(estacion);
                break;
            case "VERANO":
                System.out.println(estacion);
                break;
            case "OTOÑO":
                System.out.println(estacion);
                break;
            case "INVIERNO":
                System.out.println(estacion);
                break;
            default:
                System.out.println("La estación del año no existe");
         */
        }
    }
}
